### ISSUE TITLE
ubuntu 20.04 LTS on Win11 WSL2环境起服务失败

### ISSUE THREAD

**Issue by ruijieguo** [alibaba/havenask#136]
panda@docker-desktop:~/havenask$ ./ha3_install/hape start havenask
[2023-09-12 13:12:39,414] [INFO] [cluster_config.py:__init__:61]: Hape config directory: /home/panda/havenask/ha3_install/hape_conf/default
[2023-09-12 13:12:39,416] [INFO] [cluster_config.py:init:74]: Cluster config: {
    "havenask": {
        "searcherIpList": "192.168.65.4",
        "adminIpList": "192.168.65.4",
        "qrsIpList": "192.168.65.4",
        "adminCpu": "100",
        "image": "registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:1.0.0",
        "serviceName": "havenask-sql-local",
        "adminMem": "5124",
        "allowMultiSlotInOne": "true",
        "adminHttpPort": "45700"
    },
    "swift": {
        "adminIpList": "192.168.65.4",
        "adminCpu": "100",
        "image": "registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:1.0.0",
        "workerIpList": "192.168.65.4",
        "serviceName": "havenask-swift-local",
        "adminMem": "5124",
        "swiftZkRoot": "zfs://192.168.65.4:2181/havenask"
    },
    "common": {
        "domainZkRoot": "zfs://192.168.65.4:2181/havenask",
        "processorWorkdirRoot": "/home/panda",
        "processorMode": "docker",
        "javaHome": "/opt/taobao/java",
        "dataStoreRoot": "/home/panda/havenask/havenask_data_store",
        "binaryPath": "/ha3_install",
        "hadoopHome": "/usr/local/hadoop/hadoop/"
    },
    "bs": {
        "adminIpList": "192.168.65.4",
        "adminCpu": "100",
        "image": "registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime:1.0.0",
        "workerIpList": "192.168.65.4",
        "serviceName": "havenask-bs-local",
        "adminMem": "5124"
    }
}
[2023-09-12 13:12:39,441] [INFO] [template_config.py:render:78]: Render template config [/home/panda/havenask/ha3_install/hape_conf/default] to [/home/panda/.hape_local_templates_store/default.54ab950e904787b61328186581bed50a]
[2023-09-12 13:12:39,465] [INFO] [infra_manager.py:start_zookeeper:27]: Try to connect to domainZkRoot zfs://192.168.65.4:2181/havenask
[2023-09-12 13:12:39,473] [INFO] [infra_manager.py:start_zookeeper:31]: DomainZkRoot zfs://192.168.65.4:2181/havenask can be visited
No handlers could be found for logger "kazoo.client"
Traceback (most recent call last):
  File "./ha3_install/hape", line 33, in <module>
    cli()
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/commands/common.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/commands/start_cmd.py", line 24, in havenask
    hape_cluster = command_init(kwargs)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/commands/common.py", line 28, in command_init
    hape_cluster = HapeCluster(cluster_config)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/clusters/hape_cluster.py", line 21, in __init__
    self.swift_appmaster = SwiftAdmin(HapeCommon.SWIFT_KEY, self.cluster_config)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/clusters/swift/swift.py", line 14, in __init__
    super(SwiftAdmin, self).__init__(key, cluster_config)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/clusters/hippo_appmaster.py", line 55, in __init__
    self._proc_zfs_wrapper = FsWrapper(self._cluster_config.get_domain_config_param(HapeCommon.COMMON_CONF_KEY, "domainZkRoot"), "zfs")
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/utils/fs_wrapper.py", line 229, in __init__
    self._client = FsWrapper.FS_CLS[type](root_address, extend_attrs = extend_attrs)
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/hape_libs/utils/fs_wrapper.py", line 173, in __init__
    self._client.start()
  File "/home/panda/havenask/ha3_install/usr/local/lib/python/site-packages/kazoo/client.py", line 635, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out

**Comment by dyuyang** [comment]
可以用使用文档中提及的hape validate简单验证一下问题在哪
如果显示是ssh相关的问题，可以参考这篇文章，wsl ubuntu自带ssh似乎有问题，需要重装。而hape单机模式的前提是能够免密ssh本机拉起容器，所以会报错
我试验了一下，重装后是可以的
https://muthuishere.medium.com/setting-up-ssh-server-on-wsl-ee485ba46db7
